# Generated by Django 6.0.1 on 2026-01-31 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcategory',
            name='category_description',
            field=models.TextField(blank=True, max_length=255, null=True, verbose_name='Category Description'),
        ),
    ]
